### ISSUE TITLE
Large memory leak from sustained use

### ISSUE THREAD

**Issue by isiahmeadows** [nkt/atom-autocomplete-modules#100]
**OS:** macOS High Sierra
**Atom version:** 1.26.0
**Autocomplete Modules version:** 2.0.0

If you keep this open for long enough (think: using it for a few days without restarting, with active typing and everything), it begins to leak. This particular snapshot was the accumulation of a few days work in a decently sized code base (as in, about 100K SLoC worth of CoffeeScript, 150K of Ruby), and racked up about 3GB of data accumulated, about 50% directly traceable to this module.

Here's a link to the snapshot: https://drive.google.com/open?id=1GBrub7nCBL04neWFjFdHuNeKI_NiGogq

**Comment by isiahmeadows** [comment]
Note: this does *not* reproduce easily in safe mode.

**Comment by robertrossmann** [comment]
Is this module using `require()` calls or `import` statements to provide autocomplete suggestions? I briefly looked at the snapshot and there is a ton of entries pointing to Node.js `require` caches, including plaintext (string) representations of client code. It's possible that while working on a project many project modules are loaded into Atom to provide autocomplete functionality and those modules are forever persisted in the [Node cache](https://nodejs.org/dist/latest-v10.x/docs/api/modules.html#modules_caching).

If such code path exists here (I only found [this](https://github.com/nkt/atom-autocomplete-modules/blob/44cffba91ab8ae6f64c183a40303dc6dd57fd2f6/lib/utils/lookup-commonjs.js#L6), not sure if that's the culprit, though) then perhaps a solution to reduce the leak would be to require the module in a separate, disposable [VM instance](https://nodejs.org/dist/latest-v10.x/docs/api/vm.html) or by using AST parsing techniques to detect CommonJS exports (not always reliable if exports are created dynamically).

**Comment by jonyeezs** [comment]
@robertrossmann two libs I found that may help the cause: 

- https://www.npmjs.com/package/source-extract 
- https://www.npmjs.com/package/get-exports-from-file 

Will have to test them.

**Comment by isiahmeadows** [comment]
I think #126 might very well be the root cause, since the heap is very heterogenous with most of its memory being in strings and arrays, not objects. Also, the `require` cache shows pretty heavily, although it's not near the top in terms of retained memory.

**Comment by dead-claudia** [comment]
GH failed to auto-resolve this, too.
