### ISSUE TITLE
does not resolve the modules in a subdirectory

### ISSUE THREAD

**Issue by edarblanco** [nkt/atom-autocomplete-modules#104]
### Description
the modules are not recollected within a subdirectory within the project root, however when the files are together outside the folder everything works correctly

### Steps to Reproduce

1. Create express application with express-generator
2. then move everything to a folder called src except node_modules and package.json leaving the structure
/ project root
| _node_modules
| _src
    | _bin
    | _public
    | _routes
    | _views
    | _apps.js
| _package.json
3. autocomplete-modules does not resolve the modules in the src subdirectory

**Expected behavior:** Resolve de modules

**Actual behavior:** Not resolve any module

#### Console errors

```
Include any console errors from the developer tools that are related to the package.
You can open it from the command -> Window: Toggle Dev Tools

```

### Versions

System: Archlinux
Node: 10.2.1
Atom: 1.27.1
Python: 3.6.5

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by jonyeezs** [comment]
Hi the current feature doesn't cascade down the file structure, only on the first level.

It uses `readdir`, which only shows its immediate files and folders.

If you wish to dive in, you'll have to select `src` and let the autocomplete continue with the next level of suggestions.

Have a look at the README's gif

![Preview](https://cloud.githubusercontent.com/assets/3505878/7442538/9c1892cc-f11e-11e4-8070-3fa8b79beefc.gif)

**Comment by jonyeezs** [comment]
Sorry, yes i do see your issue now. It should be resolved soon.
