### ISSUE TITLE
Error installing plugin

### ISSUE THREAD

**Issue by icmsfun** [nkt/atom-autocomplete-modules#123]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]

#### Folder structure and import statement

```
.                    //Root
├── ...              // irrelevant but may want to give some more context
├── main
│   └── current.js   // current folder
└── reference.js     // file being referenced one folder up
```

```javascript
// current.js

import {some| } from '../reference'
```

```javascript
//reference.js

module.exports = { something: () => {} };
```

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

#### Console errors

```
Include any console errors from the developer tools that are related to the package.
You can open it from the command -> Window: Toggle Dev Tools

```

### Versions

Include the version of autocomplete-modules you are using.

Copy and pasting the output of `atom --version` and `apm --version` from the command line. 

Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.
Any plugins or tools used that may affect import statements.

**Comment by jonyeezs** [comment]
Hi, thank you for posting. Unfortunately providing the template is not
going to help.

Could you please explain what's happening, thank you

**Comment by jonyeezs** [comment]
I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue with the latest stable version and then please use the [issue template](../blob/master/ISSUE_TEMPLATE.md). You can also contribute directly by providing a pull request :100: :heart:!

Thank you!
