### ISSUE TITLE
Feature request: optionally use file extension

### ISSUE THREAD

**Issue by slimelabs** [nkt/atom-autocomplete-modules#19]
This is something that comes up a lot for me when working with React. I'm often requiring a .jsx file and I would rather explicitly `require('./Foo.jsx')` than do `require('./Foo')`;

Obviously this is a matter of preference to some degree, so perhaps adding a user setting for this behavior is the way to go.

**Comment by arv** [comment]
This is important for es6 modules since es6 import requires the full file names.

**Comment by isiahmeadows** [comment]
Please? It is a preference, but it seems like it should be easy to add.

**Comment by isiahmeadows** [comment]
Apparently, [it was pretty trivial](https://github.com/nkt/atom-autocomplete-modules/pull/32)...
