### ISSUE TITLE
Feature request: Ability to require from Atom Search

### ISSUE THREAD

**Issue by tnrich** [nkt/atom-autocomplete-modules#21]
This package to easily require node modules has recently become one of my favorite in sublime: https://github.com/ganemone/NodeRequirer

I think it would be awesome if this package could also emulate its dropdown behavior (which naturally comes with fuzzy search)!

Thanks

**Comment by jonyeezs** [comment]
Would a snippet work for you?

I use that and it does the job for me

```
'.source.ts':
  'import with export':
    'prefix': 'imp'
    'body': 'import { $2 } from \'$1\';'
  'import all':
    'prefix': 'impa'
    'body': 'import \'$1\';'
```

**Comment by jonyeezs** [comment]
Hi @tnrich, I kinda feel this is a deviate from the norm of autocomplete functionality.
Will you be happy with using snippets as suggested above?

And seeing that this is old and has no recent response, @nkt are you happy if we change the label to something else that won't muddy the feature issues? Perhaps [nice-to-have]

**Comment by jonyeezs** [comment]
Seeing this isn't getting any response, and not in the vein of autocomplete, this will be close.
