### ISSUE TITLE
Feature Request: Webpack alias support

### ISSUE THREAD

**Issue by axelson** [nkt/atom-autocomplete-modules#25]
I use webpack aliases heavily for imports so that I do not need too many relative url's (which break if I re-organize a file). It would be great to have these autocompleted for me. The base work appears to have been done in #23 (which is awesome).

`eslint-plugin-import` would be a good place to look for inspiration on implementation, specifically in `resolve-alias.js`: https://github.com/benmosher/eslint-plugin-import/blob/master/resolvers/webpack/resolve-alias.js

**Comment by onedesert** [comment]
:+1:

**Comment by aight8** [comment]
Wow that would be great!

**Comment by crobinson42** [comment]
This would be awesome! In webstorm, you accomplish this by right clicking on a directory and select "mark as project root" - you can do this to multiple directories, for example, if you have several webpack resolve paths.

**Comment by Tasemu** [comment]
👍  PLEASE!

**Comment by bcruddy** [comment]
Is this on any sort of road map?

**Comment by nkt** [comment]
@bcruddy hey, for now I haven't enough time to implement this feature, but I'm open for PRs
