### ISSUE TITLE
Feature Request: Check all node_modules up to project root

### ISSUE THREAD

**Issue by renke** [nkt/atom-autocomplete-modules#27]
My project directory consists of multiple sub-project directories and my root `node_module` is basically empty. It would be nice if the plugin would take all node_modules up to the project root into consideration.

Thoughts?

**Comment by luizlago** [comment]
+1

**Comment by skuridin** [comment]
Will be useful in (lernajs) monorepos. Now autocomplete works only from root `node_modules`.

**Comment by jonyeezs** [comment]
This sounds similar to  #67.

Closing it unless @renke wishes to reopen if it's not the same.
