### ISSUE TITLE
Feature request: Additional Module dirs setting

### ISSUE THREAD

**Issue by jsg2021** [nkt/atom-autocomplete-modules#3]
It would be cool if we can add directories to resolve packages too.

**Comment by nkt** [comment]
Do you mean set `NODE_PATH` variable for lookup?

**Comment by jsg2021** [comment]
Maybe, if setting that does not also drop the current lookup.  My app is bundled with webpack, and I've added my `./src/main/js` directory to the front of the resolve lookup before falling back to normal node_modules.

in my app all directories directly under `./src/main/js` can be required without various '../'

**Comment by nkt** [comment]
Yep, in node environment you can do the same using `NODE_PATH` env variable. I'll think about this feature.

**Comment by rodmax** [comment]
+ 1 for this feature
My setup is similar to @jsg2021 (I use require.js AMD modules) so it will be good to add at least one folder to resolve modules

**Comment by pho3nixf1re** [comment]
What needs to be done to support this? I may be willing to do the work of implementation @nkt with some guidance on how you think it should be accomplished.

**Comment by pho3nixf1re** [comment]
Looks like adding a check for a config value [here](https://github.com/nkt/atom-autocomplete-modules/blob/master/src/completion-provider.js#L78) would work and add it to the paths to check. What do you think?

**Comment by nkt** [comment]
@pho3nixf1re yep. We need add some interface for describing additional directories and implement support in code.
Maybe we can add some popular directories, like `vendor`, `bower_components`, etc. and add checkboxes which enables them.

**Comment by nkt** [comment]
Fixed in #22
