### ISSUE TITLE
Add support for babel-plugin-module-alias

### ISSUE THREAD

**Issue by tleunen** [nkt/atom-autocomplete-modules#40]
Would be great to add support for [babel-plugin-module-alias](https://github.com/tleunen/babel-plugin-module-alias).

I'm posting this to see if someone wants to take a look to add the support, otherwise I'll try to get some time to take a look at how to implement this.

**Comment by nkt** [comment]
Hey. If you don't want to unpack presets, it's pretty easy to implement this. PR is welcome ;)

**Comment by tleunen** [comment]
I'll work on it tomorrow. Indeed, it should be trivial. 

Any hint on how to easily test my local branch/setup in my atom?

**Comment by nkt** [comment]
Run `apm develop autocomplete-modules` then run `atom path/to/your/project --dev` and development version of plugin will be activated.

**Comment by jrnail23** [comment]
@tleunen, what's the story behind babel-plugin-module-alias vs. babel-plugin-module-resolver (looks like you're the author of both)?
- What's the difference between the two?
- The [alias npm module](https://www.npmjs.com/package/babel-plugin-module-alias)'s repo link redirects to the resolver github repo... should we expect `atom-autocomplete-modules` to support both?

**Comment by tleunen** [comment]
Both are the same, think of babel-plugin-module-resolver as a new version (v2) of module-alias.

I changed the name because the plugin now does more than just aliasing. My PR is supporting both, but we can decide to only support the new version actually...

**Comment by jrnail23** [comment]
IMO, you should continue supporting both, at least for a minimum transition/deprecation period.
It would probably also be a good idea to update the settings UI to reflect the support for both.

Oh, and thanks for the lightning quick reply!

**Comment by tleunen** [comment]
Yep, that's exactly what I was thinking.. Keeping the support of both module-resolver/alias here, and in a few weeks/months, the support for module-alias could be dropped.

Do you mean it would be best to keep the old settings in the autocomplete settings so old users keeps it enabled (if it was enabled)?

**Comment by jrnail23** [comment]
actually, I was only thinking about the descriptions in the settings UI
