### ISSUE TITLE
Issue completing scoped packages

### ISSUE THREAD

**Issue by darobin** [nkt/atom-autocomplete-modules#44]
Reproduce:

1. Have a scoped package installed in npm
1. Type enough to trigger completion on it, eg. `import whatever from '@`
1. This will bring up a completion list with `@foo`
1. Hit tab to insert the suggestion
1. You get  `import whatever from '@@foo';`

Expectation: that the `@` not be doubled.

**Comment by nkt** [comment]
Yep, I know about this. I'm going to rewrite autocomplete mechanism, but don't have enough time for this.
PRs are welcome!

**Comment by darobin** [comment]
From a quick look at the code it isn't clear to me if that comes from this module or whatever calls it. If you have some pointers, I'm happy to give it a shot. (Also happy to try without pointers but it might take longer to get started.)
