### ISSUE TITLE
Not Working with new version of Atom

### ISSUE THREAD

**Issue by EQuimper** [nkt/atom-autocomplete-modules#47]
Hey is not working anymore with the version 1.10.2 of Atom

**Comment by nkt** [comment]
Hi. I'll check this as soon as possible.

**Comment by nkt** [comment]
I guess it's again because of babel-language plugin

**Comment by EQuimper** [comment]
Thank you for the update but still not working for me. Gonna look if it's not from my side

**Comment by nkt** [comment]
Can you show me some code and list of your plugins?

**Comment by EQuimper** [comment]
It's ok now I just restart Atom after the update now it's working ;)
