### ISSUE TITLE
100% CPU usage after update to 1.6.2

### ISSUE THREAD

**Issue by PavelVanecek** [nkt/atom-autocomplete-modules#49]
So today I upgraded autocomplete-modules from 1.6.1 to 1.6.3. When I open a javascript file and start typing, after few seconds my CPU is on 100% usage and editor window frozen. As soon as I disable the package, all is okay.

OSX 10.11.6
Atom.io 1.9.6
Quite a few plugins

I tried to figure out what is wrong but I am not able to capture profiling timeline because devtools freeze too :/ Do you have any idea how to find a cause of this?

Edit: I just tried to:
- update Atom to 1.10.2 - issue still there
- downgrade to autocomplete-modules 1.6.2 - issue still there
- downgrade to autocomplete-modules 1.6.1 - no issue

**Comment by maximeaubaret** [comment]
I'm having the same issue. 
I'm running Atom 1.10.2 compiled from source and autocomplete-modules 1.6.3. 
The problem even seems to appear when all other modules are deactivated.

**Comment by nkt** [comment]
@PavelVanecek @maximeaubaret thanks for reporting. Can you tell me your settings of `autocomplete-modules`?
Now I'm completely rewriting this plugin, but I need to know, why it's buggy now.

**Comment by PavelVanecek** [comment]
My configuration: 
![image](https://cloud.githubusercontent.com/assets/1100170/18671680/425850cc-7f45-11e6-80f0-b4b95cd061ec.png)

All off, input fields default

**Comment by maximeaubaret** [comment]
Same thing for me here :)

**Comment by dlmanning** [comment]
Seeing the same thing. Here's a profile snapshot:

![image](https://cloud.githubusercontent.com/assets/2949092/18856705/07d2061a-8412-11e6-8003-977acd953d9f.png)

which I believe is a reference to: https://github.com/nkt/atom-autocomplete-modules/blob/master/src/completion-provider.js#L12

No idea why that RegExp (which hasn't changed since June), would suddenly be taking 9s+, but there it is.

**Comment by pdf** [comment]
Can confirm that reverting 3e2dba1 stops the editor from locking up when editing strings.
