### ISSUE TITLE
Add support for .babelrc in subfolders

### ISSUE THREAD

**Issue by aihornmac** [nkt/atom-autocomplete-modules#57]
Currently it only recognizes module-resolver defined in `/.babelrc`. However, I have some `.babelrc` files in subfolders, like `/editor/.babelrc`, which are not recognized. Please add support if possible. Thank you for your dedication!

**Comment by eugene-moroz** [comment]
actually, I looked into source and found it uses `find-babel-config` module, still trying to debug and identify why it is not working properly..

**Comment by jonyeezs** [comment]
This has now been fixed in `v1.13.0`
