### ISSUE TITLE
Feature request: Support for babel-root-slash-import

### ISSUE THREAD

**Issue by jeanfredrik** [nkt/atom-autocomplete-modules#58]
I’m using the [babel-root-slash-import plugin](https://github.com/mantrajs/babel-root-slash-import) so I can write

```javascript
import SomeExample from '/some/example.js';
```

instead of

```javascript
import SomeExample from '../../../some/example.js';
```

I define the root path in `.babelrc` like this:

```javascript
{
  "plugins": [
    ["babel-root-slash-import", {
      "rootPathSuffix": "src/js"
    }]
  ]
}
```

This package would be even more helpful to me if it worked with this plugin! I can try to do a pull request, but I’m not sure where to start.

**Comment by nkt** [comment]
Are you sure [babel-plugin-module-resolver](https://github.com/tleunen/babel-plugin-module-resolver) won't help you? This plugin already supported.

**Comment by jeanfredrik** [comment]
It doesn't look like it. It doesn't seem to support the same path syntax (leading slash for the root directory). I would have to add all top level directories and remove the trailing slashes in each import statement in my app.
