### ISSUE TITLE
How to instal and config our Packages

### ISSUE THREAD

**Issue by dKslaWn** [nkt/atom-autocomplete-modules#68]
I can not instal ou Packages ! The autocomplete does not work in atom. Please explain better configuration and instal.

**Comment by jonyeezs** [comment]
atom package installation are all the same. This does not do anything different.

There are strange behaviours with atom packages.

Try uninstalling and installing it again.

Better yet, if you could provide more information such as this https://github.com/atom/autocomplete-html/blob/master/ISSUE_TEMPLATE.md that would be awesome!
