### ISSUE TITLE
Deprecation warning in latest Atom

### ISSUE THREAD

**Issue by j-f1** [nkt/atom-autocomplete-modules#69]
Argument to `path.dirname` must be a string

```
Object.dirname (/Applications/Atom.app/Contents/Resources/app/src/electron-shims.js:9:10)
CompletionProvider.getSuggestions (/Users/hayfields/.atom/packages/autocomplete-modules/src/completion-provider.js:54:50)
<unknown> (<embedded>:40190:60)
Array.forEach (native)
AutocompleteManager.getSuggestionsFromProviders (<embedded>:40166:23)
AutocompleteManager.findSuggestions (<embedded>:40155:25)
```

**Comment by jonyeezs** [comment]
The line you are refering to is `path.dirname(editor.getPath())`

getPath()
> Returns the String path of this editor's text buffer.

So it should work.

Could you help give more context please. See https://github.com/atom/autocomplete-html/blob/master/ISSUE_TEMPLATE.md for an example

**Comment by j-f1** [comment]
I can’t reproduce this anymore, so I’m closing the issue.
