### ISSUE TITLE
Support TypeScript path aliases

### ISSUE THREAD

**Issue by phaux** [nkt/atom-autocomplete-modules#75]
Example tsconfig.json:
```json
{
  "compilerOptions": {
    "paths": {
      "@app/*": [
        "app/*"
      ]
    }
  }
}
```

After typing `@app/` it should suggest files from the app root, regardless of where the current file is located.

**Comment by phaux** [comment]
I discovered that typescript plugin can add imports for missing variables automatically (alt+enter via intentions package), so it's not that important anymore 😛

**Comment by jonyeezs** [comment]
@phaux which typescript plugin?   [ide-typescript](https://atom.io/packages/ide-typescript) or [atom-typescript](https://atom.io/packages/atom-typescript)?

**Comment by phaux** [comment]
both

**Comment by jonyeezs** [comment]
FYI to all who pops here: If you're using typescript, recommended packages above has better autocomplete options
