### ISSUE TITLE
Feature Request: autocomplete for export in an imported module

### ISSUE THREAD

**Issue by jonyeezs** [nkt/atom-autocomplete-modules#79]
Expected Behaviour:

```javascript
import {} from 'module';
```
when cursor is in  {} (or what ever valid format)
```javascript
import {_} from 'module';
```

It should show list of available exports
![image](https://user-images.githubusercontent.com/10862726/31757129-f6f0f42c-b4ea-11e7-88d4-fff2ce00541c.png)

We can utilize this node library [get-exports-from-file](https://github.com/capaj/get-exports-from-file)

**Comment by jonyeezs** [comment]
I don't mind having a go at this

could you kindly add a `Hacktoberfest` label to this please :smile:?

**Comment by nkt** [comment]
sure!
