### ISSUE TITLE
Option to not truncate `./module/index.js` to `./module`

### ISSUE THREAD

**Issue by isiahmeadows** [nkt/atom-autocomplete-modules#82]
For ES6 projects not dependent on Node, this would be incredibly useful.

**Comment by jonyeezs** [comment]
It should not do that now.

Instead should see the index.js in the autocomplete

![works-for-me](https://user-images.githubusercontent.com/10862726/44467002-13dda280-a665-11e8-9405-3da02ba337f0.gif)

**Comment by jonyeezs** [comment]
t should not do that now.

Instead should see the index.js in the autocomplete

![leave-index](https://user-images.githubusercontent.com/10862726/44467054-42f41400-a665-11e8-9d3d-0eed28bd2492.gif)

This is on version 2.1.4
