### ISSUE TITLE
Support parent directory

### ISSUE THREAD

**Issue by evgenyrodionov** [nkt/atom-autocomplete-modules#9]
Thanks for module, but it doesn't support parent directories (`../modules/utils`, for example)

**Comment by nkt** [comment]
It is. Please describe your case better.

**Comment by theaqua** [comment]
<img width="744" alt="screenshot 2015-07-10 19 00 26" src="https://cloud.githubusercontent.com/assets/775692/8622816/f9a4ba2c-2735-11e5-8b30-2373026a8552.png">

**Comment by theaqua** [comment]
It's partly working. See this video: https://www.dropbox.com/s/qa82qv80o0rt75g/atom-autocomplete-modules.mov?dl=0

I have tree with files `index.jsx`, `landing.jsx`, `request.jsx`, etc. When I type `../`, it doesn't autocomplete, only when I'm type `../l` (`landing`). But when I type `../../` it shows me everything: `app`, `alt`, `router`.

**Comment by nkt** [comment]
I see. When I was developing this, I got your case but it's limitation of autocomplete-plus package, so I can't fix this. I just don't got `../` in autocomplete provider.

**Comment by jeancroy** [comment]
If `../l` work then i'm guessing it's doing something like
 - Go up one folder
 - Build a list of file & folder
- Filter list for `l`

Then `../` does
- Go up one folder & build file list
- filter list for `"" - empty string` and that return nothing.

Maybe one thing that can help is to return full list of suggestion when prefix is empty.
Somewhere around this line

https://github.com/nkt/atom-autocomplete-modules/blob/c9a95ed01879de76171202ddbc3ac7f35402e146/src/completion-provider.js#L65

**Comment by benogle** [comment]
> but it's limitation of autocomplete-plus package

Can you elaborate on the limitation in autocomplete-plus?

**Comment by samet-karaibryamov** [comment]
I believe this was resolved by #60.
