### ISSUE TITLE
Search only begins when I type a character

### ISSUE THREAD

**Issue by GuyHadas** [nkt/atom-autocomplete-modules#90]
For example when I do `require('../)`, I expect to see what current directory I'm in with available files to pick from, but I have to first do `require('../a)` to see anything...

**Comment by jonyeezs** [comment]
Hi could you give more details. ie: version of atom-autocomplete-module and any errors from the developer tools would be helpful.

**Comment by jonyeezs** [comment]
cannot reproduce.

And due to in-activeness, this issue will be closed.

Please do mention if this needs to be reopen.
