### ISSUE TITLE
autocomplete named imports

### ISSUE THREAD

**Issue by Venugopal46** [nkt/atom-autocomplete-modules#91]
Need support for autocompleting named imports like vscode does.

![image](https://user-images.githubusercontent.com/7404447/35090260-19669fbe-fc5f-11e7-8bef-007c88e6fe0c.png)

**Comment by jonyeezs** [comment]
It does support that. Is it not working for you?

**Comment by Venugopal46** [comment]
No it isn't. I uninstalled all other packages(not core packages) incase any of it messing this feature but no luck.

**Comment by jonyeezs** [comment]
Ah ok sorry. You are right. 

It doesn't support it. 

How is that getting imported? Is that an alias? 

I'm not familiar with vue nor how it's tool stack works.

**Comment by Venugopal46** [comment]
It's just another npm package in a simple js file. I'm hoping these named imports should work without any extra setup. It is working for local file imports though.

**Comment by jonyeezs** [comment]
Maybe I'm still don't undestand what you're refering too.

Let's get on the same page. I've named them accordingly in the code:

```
import { named export } from 'imported module'
```

(_referencing from [mdn import](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import)_)

So is the imported module or the named export is not getting autocompleted?

**Comment by jonyeezs** [comment]
autocomplete-modules is only activate on certain packages.

Are you using any of these packages?
* language-javascript
* language-babel
* language-coffee-script
* language-ts
* language-typescript-grammars-only
* atom-typescript

**Comment by Venugopal46** [comment]
I've got 
- language-javascript
- language-babel
- language-coffee-script

**Comment by jonyeezs** [comment]
Hi @Venugopal46, I think I know what the problem might be.

Could you help me run one more test?

Open your dev-tool (Window: Toggle Dev Tools), and reproduce the step and post any of the errors you might see. Thank you!

**Comment by Venugopal46** [comment]
![image](https://user-images.githubusercontent.com/7404447/36094764-85caa4e2-1015-11e8-9d5d-99d5bd867c0d.png)

Sorry for the late response.
I see this error for all the npm packages and all of the package.json files exist in node_modules filder

**Comment by jonyeezs** [comment]
Closing this as no response. If still not working we can review to open this again.

**Comment by Venugopal46** [comment]
I see it's working. Thank you.
