### ISSUE TITLE
Export Module Completion error

### ISSUE THREAD

**Issue by callain** [nkt/atom-autocomplete-modules#96]
Hello, here is the issue I have when I use this plugin.

### Description

Adding import creates a lot of error, and makes Atom freeze when I import multiples variables or functions on the same line.

### Steps to Reproduce

1. Create a test file 

test.js
```javascript
export const test = () => "Hello";

export const test2 = () => "World";
```

2. Try to include test from another file

index.js
```javascript
import {test} from "./test";
```

3. Select the text inside the brackets and edit it to add test2 to have it like this

```javascript
import {test, test2} from "./test";
```

**Expected behavior:** It works fine

**Actual behavior:** It prints a lot of log inside the developer tools console. It is even worse when you add import with long names on the same line, Atom freeze. And I can only force close it.

**Reproduces how often:** Every time

#### Console errors

<img width="769" alt="image" src="https://user-images.githubusercontent.com/7001103/36684013-6eec9856-1b1f-11e8-91fc-e505ba8f4a8e.png">

### Versions
macOS High Sierra

Atom : 1.25.0-beta2 x64
autocomplete-modules : 1.11.0

### Additional Information

I'm not sure if this an Atom Issue or autocomplete-modules issue.
I will be glad to help :)

**Comment by jonyeezs** [comment]
> I will be glad to help :)

@callain 
Would you like to try to put in a PR for this?

Something happened while it was trying to `require` test.js.

**Comment by callain** [comment]
I will try ;)

**Comment by jonyeezs** [comment]
Since changes to the package. This should be tested to see if it is still an issue.

**Comment by jonyeezs** [comment]
Tested and working on version 2.2.0
